<a href="https://colab.research.google.com/github/maruwrks/Deep-Learning-Task/blob/main/support_vector_machines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear SVM Classification

### Generating some linearly separable data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier

X = np.array([[1, 2], [1, 4], [1, 0], [4, 2], [4, 4], [4, 0]])
y = np.array([0, 0, 0, 1, 1, 1]) # Example labels

### Iris dataset example

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)]  # petal length, petal width
y = (iris["target"] == 2).astype(np.float64)  # Iris virginica

### Soft Margin Classification using LinearSVC

In [3]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC(loss="hinge", C=1, random_state=42, max_iter=20000)
lin_svc.fit(X, y)

lin_svc.predict([[1.6, 0.5]]) # Example prediction
lin_svc.predict([[5.5, 1.7]])

array([1.])

### Using SGDClassifier (Linear SVM)

In [4]:
sgd_clf = SGDClassifier(loss="hinge", alpha=1/100, max_iter=1000, tol=1e-3, random_state=42)
sgd_clf.fit(X, y)

sgd_clf.predict([[5.5, 1.7]])

array([1.])

##Nonlinear SVM Classification

### Polynomial Features

In [5]:
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=100, noise=0.15, random_state=42)

In [6]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

polynomial_svm_clf = Pipeline([
    ("poly_features", PolynomialFeatures(degree=3)),
    ("scaler", StandardScaler()),
    ("svm_clf", LinearSVC(C=10, loss="hinge", random_state=42, max_iter=20000))
])

polynomial_svm_clf.fit(X, y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf',
                 LinearSVC(C=10, loss='hinge', max_iter=20000,
                           random_state=42))])

### Polynomial Kernel

In [7]:
from sklearn.svm import SVC
poly_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5, random_state=42))
])
poly_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly', random_state=42))])

### Gaussian RBF Kernel

In [8]:
rbf_kernel_svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="rbf", gamma=5, C=0.001, random_state=42))
])
rbf_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=0.001, gamma=5, random_state=42))])

##SVM Regression

### Linear SVM Regression

In [9]:
# Generate some linear-looking data
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

from sklearn.svm import LinearSVR
svm_reg = LinearSVR(epsilon=1.5, random_state=42)
svm_reg.fit(X, y.ravel()) # .ravel() is needed for y to be 1D

svm_reg.predict([[1.5]]) # Example prediction

array([8.30265816])

### Nonlinear SVM Regression

In [10]:
# Generate some nonlinear data (quadratic)
X = 2 * np.random.rand(100, 1) - 1
y = 0.2 + 0.1 * X + 0.5 * X**2 + np.random.randn(100, 1) / 10

from sklearn.svm import SVR
svm_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X, y.ravel())

SVR(C=100, degree=2, kernel='poly')

In [11]:
svm_poly_reg.predict([[0.5]]) # Example prediction

array([0.35915867])

In [12]:
svm_rbf_reg = SVR(kernel="rbf", gamma=0.1, C=100, epsilon=0.1)
svm_rbf_reg.fit(X, y.ravel())

SVR(C=100, gamma=0.1)

In [13]:
svm_rbf_reg.predict([[0.5]]) # Example prediction

array([0.39689552])